// Mocks generated by Mockito 5.4.6 from annotations
// in zent_fe/test/location_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zent_fe/services/location_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FusedLocationProviderClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFusedLocationProviderClient extends _i1.Mock
    implements _i2.FusedLocationProviderClient {
  MockFusedLocationProviderClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> requestLocationUpdates(
    _i2.LocationRequest? request,
    _i2.LocationCallback? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationUpdates, [request, callback]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeLocationUpdates(_i2.LocationCallback? callback) =>
      (super.noSuchMethod(
            Invocation.method(#removeLocationUpdates, [callback]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GeofencingClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeofencingClient extends _i1.Mock implements _i2.GeofencingClient {
  MockGeofencingClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addGeofences(List<_i2.Geofence>? geofences) =>
      (super.noSuchMethod(
            Invocation.method(#addGeofences, [geofences]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeGeofences(List<String>? geofenceIds) =>
      (super.noSuchMethod(
            Invocation.method(#removeGeofences, [geofenceIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [LocationCallback].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationCallback extends _i1.Mock implements _i2.LocationCallback {
  MockLocationCallback() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onLocationResult(_i2.Location? location) => super.noSuchMethod(
    Invocation.method(#onLocationResult, [location]),
    returnValueForMissingStub: null,
  );

  @override
  void onLocationError(Exception? exception) => super.noSuchMethod(
    Invocation.method(#onLocationError, [exception]),
    returnValueForMissingStub: null,
  );
}
