name: Check merge code

# This triggers the workflow when a PR is opened against 'main' or 'test'
on:
  pull_request:
    branches:
      - main
      - test

jobs:
  check_code:
    name: Format, Analyze, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        # Fails the pipeline if code isn't formatted correctly
        run: dart format --set-exit-if-changed .

      - name: Analyze Code
        # Checks for syntax errors and unused variables
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test