# name: Check merge code

# # This triggers the workflow when a PR is opened against 'main' or 'test'
# on:
#   pull_request:
#     branches:
#       - main
#       - test

# jobs:
  # build_release:
  #   name: Build and Create GitHub Release
  #   needs: check_code # Ensures code passes before building
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Java
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: 'zulu'
  #         java-version: '17'
  #
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #         cache: true
  #
  #     - name: Install Dependencies
  #       run: flutter pub get
  #
  #     - name: Build Release APK
  #       run: flutter build apk --release
  #
  #     - name: Create GitHub Release and Upload APK
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: v1.0.${{ github.run_number }} # Auto-generates a version number
  #         name: Release v1.0.${{ github.run_number }}
  #         files: build/app/outputs/flutter-apk/app-release.apk
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Hello World Action

on:
  workflow_dispatch: 

jobs:
  say-hello:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Print the greeting
        run: echo "Hello, World!"